spring:
  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASSWORD}@mongodb:27017/4-key-metrics

logging:
  config: classpath:log4j2-file-and-console.xml

aes:
  key: ${AES_KEY}
  iv: ${AES_IV}