version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15.2
  aws-cli: circleci/aws-cli@1.3.2

jobs:
  test_build_push:
    docker:
      - image: circleci/node:14.15.4

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run tests
          command: npm run test

      - run:
          name: Build artifacts
          command: npm run build:prod

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run:
          name: Build and tag Docker image
          command: |
            TAG=v${CIRCLE_BUILD_NUM}-$(date '+%Y%m%d')
            docker build -f ./Dockerfile-CircleCI -t ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO}:$TAG -t ${AWS_ECR_ACCOUNT_URL}/${AWS_ECR_REPO}:latest .

      - aws-cli/install

      - aws-ecr/ecr-login

      - aws-ecr/push-image:
          repo: ${AWS_ECR_REPO}
          tag: latest,v${CIRCLE_BUILD_NUM}-$(date '+%Y%m%d')

  deploy_to_dev:
    docker:
      - image: alpine:3.13.0

    steps:
      - run:
          name: Login and deploy
          command: echo "Waiting for implement."

workflows:
  version: 2
  test_build_push_and_deploy:
    jobs:
      - test_build_push
      - deploy_to_dev:
          requires:
            - test_build_push