version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
      resource_class: small
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'

workflows:
  version: 2
  example_workflow:
    jobs:
      - build
