name: 'Backend API test'
description: 'Run backend service API tests with MongoDB'

inputs:
  working-dir:
    description: 'The path of backend module'
    required: true

runs:
  using: "composite"
  steps:
    - name: Grant execute permission for shell scripts
      run: |
        chmod +x gradlew
        chmod +x ./scripts/*.sh
      shell: bash
      working-directory: ${{ inputs.working-dir }}

    - name: Run Gradle build task, including unit test, integration test, and lint check
      run: ./gradlew clean build
      shell: bash
      working-directory: ${{ inputs.working-dir }}
