spring:
  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASSWORD}@localhost:27017/4-key-metrics

logging:
  config: classpath:log4j2-file-and-console.xml

# Use length 16 for both key and IV
aes:
  key: ${AES_KEY}
  iv: ${AES_IV}