name: 'Backend testing'
description: 'Test backend module'

inputs:
  workspace:
    description: 'The path of backend module'
    required: true

runs:
  using: "composite"
  steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
      working-directory: ${{ inputs.workspace }}

    - name: Run Gradle test task
      run: ./gradlew build
      shell: bash
      working-directory: ${{ inputs.workspace }}

    - name: Check MongoDB initialization
      run: |
        COUNTER=0
        mongo --eval "db.stats()"
        while [[ $? -ne 0 && $COUNTER -lt 30 ]] ; do
            sleep 2
            let COUNTER+=2
            echo "Waiting for Mongo to initialize... ($COUNTER seconds so far)"
            mongo --eval "db.stats()"
        done
        echo "MongoDB has been successfully initialized".
      shell: bash

    - name: Configure MongoDB
      run: |
        mongo 4-key-metrics --eval "db.createUser({ user: '4km', pwd: '4000km', roles: [{ role: 'readWrite', db: '4-key-metrics' }]})"
        for file in `find ${{ inputs.workspace }}/src/api-test/resources/ -type f -name '*.js'`
        do
          mongo -u "4km" --authenticationDatabase "4-key-metrics" -p "4000km" 4-key-metrics < $file
        done
      shell: bash

    - name: Run API tests
      run: ./gradlew bootRun & ./gradlew apiTest
      shell: bash
      working-directory: ${{ inputs.workspace }}