name: Backend test

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/actions/backend_test/**
      - .github/workflows/backend_test.yaml

  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - .github/actions/backend_test/**
      - .github/workflows/backend_test.yaml

  workflow_dispatch:

jobs:
  backend-test:
    name: Backend module test
    runs-on: ubuntu-latest

    steps:
      - name: Setup timezone
        run: sudo timedatectl set-timezone "Asia/Shanghai"

      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: 'jdk'
          java-version: '11'
          check-latest: true

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run backend tests
        uses: ./.github/actions/backend_test
        with:
          working-dir: ./backend

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          generate-branches-badge: true

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'doc: update test coverage badge'
          add: '*.svg'

##     This step allow you to debug via SSH
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
#        with:
#          sudo: true
